# Generated by Django 3.2.9 on 2021-11-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Enter ticker', max_length=4)),
                ('ticker_price', models.IntegerField()),
                ('subscriber_email', models.TextField()),
            ],
            options={
                'ordering': ['subscriber_email', 'ticker'],
            },
        ),
    ]
