# Generated by Django 3.2.9 on 2021-11-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickermodel',
            name='ticker_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
